INSERT INTO AUTOR (NOME) VALUES ('Raphael Garcia Moreira')
INSERT INTO AUTOR (NOME) VALUES ('Monteiro Lobato')
INSERT INTO AUTOR (NOME) VALUES ('Dan Brown')


INSERT INTO LIVRO (CAPA, NOME, QUANTIDADE_PAGINAS, AUTOR_ID) VALUES ('uploaded-images\livros\uma mente brilhante.jpg',	'Uma mente brilhante', 300,	1)

INSERT INTO LIVRO (CAPA, NOME, QUANTIDADE_PAGINAS, AUTOR_ID) VALUES ('uploaded-images\livros\aprendendo java.jpg',	'Aprendendo Java', 400,	1)


INSERT INTO USUARIO (PASSWORD, USERNAME) VALUES ('$2a$10$oLYSWqxpt811d1LT6PSWiuS3Vf/zX3.I2NosMuI6uwAEp5GUvfipe', 'admin')


INSERT INTO ROLE (ROLE, USUARIO_ID) VALUES ('ROLE_BASIC', 1)


INSERT INTO EMPRESTIMO (DATA_DEVOLUCAO, DATA_EMPRESTIMO, DATA_EMPRESTIMO_FORMATADA, DATA_ENTREGA, LIVRO_ID, USUARIO_ID) VALUES ('06/02/2018', '2018-02-04 16:33:12.575', NULL,	'04/05/2018', 1, 1)
INSERT INTO EMPRESTIMO (DATA_DEVOLUCAO, DATA_EMPRESTIMO, DATA_EMPRESTIMO_FORMATADA, DATA_ENTREGA, LIVRO_ID, USUARIO_ID) VALUES ('06/02/2018', '2018-02-04 16:33:12.575', NULL,	'04/05/2018', 2, 1)